name: run-tests
on:
  push:
    branches:
      -lib-api-tests-testng
jobs:
  build:
    name: run-api-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Maven Flow Merge
        uses: maven-flow/merge@v1.2.0
      
      - name: Run API tests
        run: mvn clean test
